#pragma once 

#define VC_EXTRALEAN

#include <Windows.h>
#include <bo.h>
#include <NVR.H>
#include <dsound.h>

#define MODEL_NUMBER 1527


/*
#define UTIL_ALLOW_BIT					0x00000001
#define UTIL_EEPROM_UPDATE_BIT			0x00000002
#define UTIL_CHANGE_RNV_BIT				0x00000004
#define UTIL_EMPTY_RECYCLER_BIT			0x00000008
#define UTIL_RECYCLER_VALUE_BIT			0x00000010
#define UTIL_TITO_AUDIT_BIT				0x00000020
#define UTIL_ADD_2_CREDIT_BIT			0x00000040
#define UTIL_REFILL_COINS_BIT			0x00000080
#define UTIL_COIN_TEST_BIT				0x00000100
#define UTIL_NOTE_TEST_BIT				0x00000200
#define UTIL_PRINT_TICKET_BIT			0x00000400
#define UTIL_REREAD_BIRTHCERT_BIT		0x00000800

//For use when testing the bit.
#define UTIL_REQUEST_ALLOWED    		Share2&UTIL_ALLOW_BIT
#define UTIL_REQUEST_EEPROM_UPDATE		Share2&UTIL_EEPROM_UPDATE_BIT
#define UTIL_REQUEST_CHANGE_RNV			Share2&UTIL_CHANGE_RNV_BIT
#define UTIL_REQUEST_EMPTY_RECYCLER		Share2&UTIL_EMPTY_RECYCLER_BIT
#define UTIL_REQUEST_RECYCLER_VALUE		Share2&UTIL_RECYCLER_VALUE_BIT
#define UTIL_REQUEST_TITO_AUDIT			Share2&UTIL_TITO_AUDIT_BIT
#define UTIL_REQUEST_ADD_2_CREDIT		Share2&UTIL_ADD_2_CREDIT_BIT
#define UTIL_REQUEST_REFILL_COINS		Share2&UTIL_REFILL_COINS_BIT
#define UTIL_REQUEST_COIN_TEST 			Share2&UTIL_COIN_TEST_BIT
#define UTIL_REQUEST_NOTE_TEST 			Share2&UTIL_NOTE_TEST_BIT
#define UTIL_REQUEST_PRINT_TICKET		Share2&UTIL_PRINT_TICKET_BIT
#define UTIL_REQUEST_REREAD_BIRTHCERT	Share2&UTIL_REREAD_BIRTHCERT_BIT
*/
