//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDTUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream alarm {
            get {
                return ResourceManager.GetStream("alarm", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream attention {
            get {
                return ResourceManager.GetStream("attention", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream exit {
            get {
                return ResourceManager.GetStream("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\.
        /// </summary>
        internal static string game_data {
            get {
                return ResourceManager.GetString("game_data", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream go_back {
            get {
                return ResourceManager.GetStream("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\.
        /// </summary>
        internal static string machine {
            get {
                return ResourceManager.GetString("machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\machine.ini.
        /// </summary>
        internal static string machine_ini {
            get {
                return ResourceManager.GetString("machine_ini", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream paytrans {
            get {
                return ResourceManager.GetStream("paytrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\machine\GAME_DATA\Performance.log.
        /// </summary>
        internal static string perf_log {
            get {
                return ResourceManager.GetString("perf_log", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream reset {
            get {
                return ResourceManager.GetStream("reset", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream start {
            get {
                return ResourceManager.GetStream("start", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream util {
            get {
                return ResourceManager.GetStream("util", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream util_click {
            get {
                return ResourceManager.GetStream("util_click", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream util_exit {
            get {
                return ResourceManager.GetStream("util_exit", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream volume_snd {
            get {
                return ResourceManager.GetStream("volume_snd", resourceCulture);
            }
        }
    }
}
